---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: p4

platforms:
  - name: ubuntu-14.04
  # - name: ubuntu-16.04 # Perforce has no 16.04 packages yet. Disable from the
                         # list until xenial packages are released.
  - name: centos-7.2
  - name: centos-7.1

suites:
  - name: default
    provisioner:
      pillars:
      state_top:
        base:
          '*':
            - p4

  - name: client
    provisioner:
      pillars:
      state_top:
        base:
          '*':
            - p4.client
  - name: client-base
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - p4
        p4.sls:
          p4:
            client:
              base_install: True
      state_top:
        base:
          '*':
            - p4.client

  - name: server
    provisioner:
      pillars:
      state_top:
        base:
          '*':
            - p4.server
  - name: server-base
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - p4
        p4.sls:
          p4:
            server:
              base_install: True
      state_top:
        base:
          '*':
            - p4.server

  - name: broker
    provisioner:
      pillars:
      state_top:
        base:
          '*':
            - p4.broker
  - name: broker-base
    provisioner:
      pillars:
        top.sls:
          base:
            '*':
              - p4
        p4.sls:
          p4:
            broker:
              base_install: True
      state_top:
        base:
          '*':
            - p4.broker

  - name: p4dctl
    provisioner:
      pillars:
      state_top:
        base:
          '*':
            - p4.p4dctl
