---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    pillars:
    provisioner:
      state_top:
        base:
          '*':
            - p4
