---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  is_file_root: true

platforms:
  - name: ubuntu-14.04
  # - name: ubuntu-16.04 # Perforce has no 16.04 packages yet. Disable from the
                         # list until xenial packages are released.
  - name: centos-7.2
  - name: centos-7.1

suites:
  - name: default
    pillars:
    provisioner:
      state_top:
        base:
          '*':
            - p4
  - name: client
    pillars:
    provisioner:
      state_top:
        base:
          '*':
            - p4.client
